/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BiasRouteImport } from './routes/bias'
import { Route as MitigationRouteImport } from './routes/mitigation'
import { Route as TrainRouteImport } from './routes/train'
import { Route as UploadRouteImport } from './routes/upload'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BiasRoute = BiasRouteImport.update({
  id: '/bias',
  path: '/bias',
  getParentRoute: () => rootRouteImport,
} as any)
const MitigationRoute = MitigationRouteImport.update({
  id: '/mitigation',
  path: '/mitigation',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainRoute = TrainRouteImport.update({
  id: '/train',
  path: '/train',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bias': typeof BiasRoute
  '/mitigation': typeof MitigationRoute
  '/train': typeof TrainRoute
  '/upload': typeof UploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bias': typeof BiasRoute
  '/mitigation': typeof MitigationRoute
  '/train': typeof TrainRoute
  '/upload': typeof UploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bias': typeof BiasRoute
  '/mitigation': typeof MitigationRoute
  '/train': typeof TrainRoute
  '/upload': typeof UploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bias' | '/mitigation' | '/train' | '/upload'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bias' | '/mitigation' | '/train' | '/upload'
  id: '__root__' | '/' | '/bias' | '/mitigation' | '/train' | '/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BiasRoute: typeof BiasRoute
  MitigationRoute: typeof MitigationRoute
  TrainRoute: typeof TrainRoute
  UploadRoute: typeof UploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bias': {
      id: '/bias'
      path: '/bias'
      fullPath: '/bias'
      preLoaderRoute: typeof BiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mitigation': {
      id: '/mitigation'
      path: '/mitigation'
      fullPath: '/mitigation'
      preLoaderRoute: typeof MitigationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/train': {
      id: '/train'
      path: '/train'
      fullPath: '/train'
      preLoaderRoute: typeof TrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BiasRoute: BiasRoute,
  MitigationRoute: MitigationRoute,
  TrainRoute: TrainRoute,
  UploadRoute: UploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
